version: 2.1

executors:
  java-11:
    docker:
      - image: circleci/openjdk:11-jdk

orbs:
  gradle: circleci/gradle@2.1.0
  docker: circleci/docker@1.0.1

jobs:
  Build:
    executor: java-11
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run: ./gradlew --no-daemon clean build
      - persist_to_workspace:
          root: .
          paths:
            - build/libs/

workflows:
  Build-Publish:
    jobs:
      - Build
      - docker/publish:
          name: release
          registry: $DOCKER_REGISTRY
          image: $CIRCLE_PROJECT_REPONAME
          tag: $VERSION
          deploy: true
          context: global
          after_checkout:
            - attach_workspace:
                at: .
          before_build:
            - checkout
            - run: echo "export VERSION=$(echo ${CIRCLE_BRANCH}-$(date '+%Y-%m-%d-%H%M')-${CIRCLE_SHA1:0:7}-${CIRCLE_WORKFLOW_ID:0:4} | tr '/' '.' )" >> $BASH_ENV
            - run:
                name: Tag git commit with build version and push to github
                command: |
                  git config --global push.default simple
                  git config --global user.email "circleci@entur.no"
                  git config --global user.name "circleci"
                  echo $VERSION
                  git tag $VERSION
                  git push origin $VERSION
          requires:
            - Build
