{{- if .Values.PodDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "name.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
spec:
  minAvailable: {{ .Values.PodDisruptionBudget.minAvailable | default "50%" }}
  selector:
    matchLabels:
      {{- include "common.matchLabels" . | indent 6 }}
{{- end }}