apiVersion: v1
data:
  lillestromApiKey: {{ .Values.secrets.app.lillestromApiKey }}
kind: Secret
metadata:
  annotations:
    harness.io/skip-versioning: "true"
  name: {{ .Values.secrets.app.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque